version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - npm install

build: off

before_test:
  - node -v
  - npm -v

test_script:

after_test:
  - node_modules/.bin/webpack -d
  - node webpack/dist
  - 7z a -r nvm$dev.zip ./tmp/dist/*
  - node_modules/.bin/webpack -p
  - node webpack/dist
  - 7z a -r nvm$.zip ./tmp/dist/*

artifacts:
  - path: "*.zip"
    name: Distro package(s)
