version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - npm install

build: off

before_test:
  - node -v
  - npm -v

test_script:
  - node -p -e "Boolean(process.stdout.isTTY)"

after_test:
  - node_modules/.bin/webpack -d
  - node webpack/dist
  - 7z a -r nvm$dev.zip ./tmp/dist/*
  - node_modules/.bin/webpack -p
  - node webpack/dist
  - 7z a -r nvm$.zip ./tmp/dist/*
  - tmp\cli v
  - copy /b bin\* %APPDATA%\nvm$
  - tmp\cli ?
  - tmp\cli ls
  - tmp\cli a
  - tmp\cli ls r
  - tmp\cli i
  - tmp\cli ls
  - tmp\cli i i
  - tmp\cli ls
  - tmp\cli i 0 x86
  - tmp\cli ls
  - tmp\cli which
  - tmp\cli use none
  - tmp\cli ls
  - tmp\cli ls x86
  - tmp\cli ls x64
  - tmp\cli where
  - tmp\cli d
  - tmp\cli d .
  - tmp\cli ls
  - tmp\cli o x86
  - tmp\cli o x64
  - tmp\cli o .
  - tmp\cli ls
  - dir %APPDATA%\nvm$
  - dir %APPDATA%\nvm$\that
  - tmp\cli b
  - tmp\cli b .

artifacts:
  - path: "*.zip"
    name: Distro package(s)
