version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - npm install

build: off

before_test:
  - node -v
  - npm -v

test_script:
  - node webpack -d
  - node webpack/dist
  - 7z a -r nvm$dev.zip ./tmp/dist/*
  - node webpack -p
  - node webpack/dist
  - 7z a -r nvm$.zip ./tmp/dist/*

after_test:
  - tmp\cli v
  - reg query HKCU\Environment /v Path /z
  - tmp\dist\setup <NUL
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - timeout 3
  - reg query HKCU\Environment /v Path /z
  - tmp\cli ?
  - tmp\cli ls
  - tmp\cli a
  - tmp\cli ls r
  - tmp\cli i
  - tmp\cli ls
  - tmp\cli i lts
  - tmp\cli ls
  - tmp\cli i x86 lts
  - tmp\cli ls
  - tmp\cli i i
  - tmp\cli ls
  - tmp\cli i 0 x86
  - tmp\cli i 0 x64
  - tmp\cli ls
  - tmp\cli which
  - tmp\cli use none
  - tmp\cli ls
  - tmp\cli ls x86
  - tmp\cli ls x64
  - tmp\cli where
  - tmp\cli d
  - tmp\cli d .
  - tmp\cli ls
  - tmp\cli use x86 lts
  - node webpack\dist sfx
  - copy /b tmp\sfx\nvm$.exe .\nvm$86.exe
  - tmp\cli use lts
  - tmp\cli ls
  - node webpack\dist sfx
  - copy /b tmp\sfx\nvm$.exe .\nvm$64.exe
  - tmp\cli o
  - tmp\cli o x86
  - tmp\cli o x86 .
  - dir %USERPROFILE%\.nvm$
  - dir %USERPROFILE%\.nvm$\that
  - tmp\cli b
  - tmp\cli b .
  - reg query HKCU\Environment /v Path /z

artifacts:
  - path: "*.zip"
    name: Distro package(s)
  - path: nvm$*.exe
    name: SFX installation package(s)
