version: 1.0.{build}-{branch}

cache:
  - node_modules

install:
  - npm install

build: off

before_test:
  - node -v
  - npm -v

test_script:

after_test:
  - node_modules/.bin/webpack -d
  - node webpack/dist
  - 7z a -r nvm$dev.zip ./tmp/dist/*
  - node_modules/.bin/webpack -p
  - node webpack/dist
  - 7z a -r nvm$.zip ./tmp/dist/*
  - tmp\cli v
  - copy /b bin\* %APPDATA%\nvm$
  - tmp\cli use none
  - tmp\cli ls
  - tmp\cli ls r
  - tmp\cli ls i
  - tmp\cli ls
  - tmp\cli o
  - tmp\cli i 0 x86
  - tmp\cli ls
  - tmp\cli d
  - tmp\cli d .
  - tmp\cli ls
  - tmp\cli b
  - tmp\cli b .

artifacts:
  - path: "*.zip"
    name: Distro package(s)
