#
# Autogenerated commands list
#
cmd.list
  stage: stage
  require './help'
  require './index'
  require './install'
  require './ls'
  require './remove'
  require './setup'
  require './use'
  require './ver'
  require './which'
  require './www'
