#
# Autogenerated commands list
#
require '../tools/cmd'
.list
  stage: require '../tools/stage'
  require './help'
  require './index'
  require './install'
  require './ls'
  require './remove'
  require './setup'
  require './use'
  require './ver'
  require './www'
