#
# Autogenerated commands list
#
require '../tools/cmd'
.list
  stage: require '../tools/stage'
  require './help'
  require './index'
  require './install'
  require './setup'
  require './use'
  require './ver'
