fs = require 'fs'
path = require 'path'

ext = '.coffee'
s = """
#
# Autogenerated commands list
#
cmd = require '../tools/cmd'


"""
fs.readdirSync path.join __dirname, '../src/cmd'
.forEach (f)->
  return if ext!=path.extname f
  f = path.basename f, ext
  return if 'index'==f
  s+="cmd require './#{f}'\n"

fs.writeFileSync path.join(__dirname, '../src/cmd/index.coffee'), s
