name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Setup node
      uses: actions/setup-node@v1
    -
      run:  npm install
    -
      name: Build with Rollup
      run:  npm run build
